import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import settings


def _send_email(subject: str, body: str, to: str) -> bool:
    if not all([settings.SMTP_HOST, settings.SMTP_USER, settings.SMTP_PASSWORD, to]):
        return False
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = settings.SMTP_USER
        msg["To"] = to
        msg.attach(MIMEText(body, "html"))

        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
            server.sendmail(settings.SMTP_USER, to, msg.as_string())
        return True
    except Exception:
        return False


async def send_critical_alert(incident: dict) -> bool:
    subject = f"[SENTINEL ALERT] Critical Security Incident: {incident.get('title', 'Unknown')}"
    body = f"""
    <h2 style="color:#dc2626;">⚠️ CRITICAL SECURITY INCIDENT DETECTED</h2>
    <p><strong>Title:</strong> {incident.get('title')}</p>
    <p><strong>Type:</strong> {incident.get('incident_type', '').replace('_', ' ').title()}</p>
    <p><strong>Severity:</strong> <span style="color:#dc2626;font-weight:bold;">CRITICAL</span></p>
    <p><strong>Affected Systems:</strong> {incident.get('affected_systems', 'N/A')}</p>
    <p><strong>Reporter:</strong> {incident.get('reporter_name')} ({incident.get('reporter_email')})</p>
    <hr>
    <p><strong>Description:</strong><br>{incident.get('description', '')}</p>
    <hr>
    <p>Log in to SENTINEL to view the full incident and response playbook.</p>
    <p style="color:#666;font-size:12px;">Generated by SENTINEL — AI Incident Response Platform</p>
    """
    return _send_email(subject, body, settings.ALERT_EMAIL)


async def send_peca_reminder(incident: dict) -> bool:
    subject = f"[SENTINEL] PECA 2016 Reporting Required — Action Needed: {incident.get('title', '')}"
    body = f"""
    <h2 style="color:#d97706;">📋 PECA 2016 REPORTING OBLIGATION</h2>
    <p>The following incident may require reporting under Pakistan's Prevention of Electronic Crimes Act (PECA) 2016:</p>
    <p><strong>Incident:</strong> {incident.get('title')}</p>
    <p><strong>Reason:</strong> {incident.get('peca_reason', 'See incident details')}</p>
    <hr>
    <h3>FIA Cybercrime Wing Contact:</h3>
    <ul>
        <li>Website: <a href="https://report.fia.gov.pk">report.fia.gov.pk</a></li>
        <li>Helpline: 0800-02345</li>
        <li>Email: cybercrime@fia.gov.pk</li>
    </ul>
    <p><em>Consult legal counsel to confirm your specific obligations under PECA 2016.</em></p>
    <p style="color:#666;font-size:12px;">Generated by SENTINEL — AI Incident Response Platform</p>
    """
    return _send_email(subject, body, settings.ALERT_EMAIL)


async def send_test_email() -> bool:
    subject = "[SENTINEL] Test Email — Configuration Working"
    body = """
    <h2 style="color:#16a34a;">✅ SENTINEL Email Configuration Working</h2>
    <p>This test email confirms your SENTINEL notification settings are configured correctly.</p>
    <p>You will receive alerts here for:</p>
    <ul>
        <li>Critical severity incidents</li>
        <li>PECA 2016 reporting obligations</li>
    </ul>
    <p style="color:#666;font-size:12px;">Generated by SENTINEL — AI Incident Response Platform</p>
    """
    return _send_email(subject, body, settings.ALERT_EMAIL)
